# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 6) do

  create_table "picks", :force => true do |t|
    t.column "player_id", :integer
    t.column "team_id", :integer
    t.column "pick_number", :integer, :default => 0, :null => false
  end

  add_index "picks", ["player_id"], :name => "fk_picks_players"
  add_index "picks", ["team_id"], :name => "fk_picks_teams"

  create_table "players", :force => true do |t|
    t.column "yahoo_ref", :integer, :default => 0
    t.column "player", :string
    t.column "team", :string
    t.column "pos", :string
    t.column "status", :string
    t.column "rank", :integer
    t.column "IP", :float
    t.column "W", :integer
    t.column "SV", :integer
    t.column "K", :integer
    t.column "ERA", :float
    t.column "WHIP", :float
    t.column "R", :float
    t.column "HR", :integer
    t.column "RBI", :integer
    t.column "SB", :integer
    t.column "AVG", :float
    t.column "orank", :integer
    t.column "ab", :string
  end

  add_index "players", ["pos"], :name => "posindex"
  add_index "players", ["id"], :name => "playerindex"
  add_index "players", ["player"], :name => "players_player_index"
  add_index "players", ["pos"], :name => "players_pos_index"
  add_index "players", ["rank"], :name => "players_rank_index"

  create_table "teams", :force => true do |t|
    t.column "full_name", :string
    t.column "short_name", :string
    t.column "owner", :string
    t.column "team_yahoo_ref", :integer
    t.column "draft_order", :integer, :default => 1
  end

end
