# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 10) do

  create_table "picks", :force => true do |t|
    t.column "player_id",   :integer, :null => false
    t.column "team_id",     :integer, :null => false
    t.column "pick_number", :integer, :null => false
  end

  add_index "picks", ["team_id"], :name => "fk_picks_teams"

  create_table "players", :force => true do |t|
    t.column "yahoo_ref", :integer, :default => 0
    t.column "player",    :string
    t.column "team",      :string
    t.column "pos",       :string
    t.column "status",    :string
    t.column "rank",      :integer, :default => 1300
    t.column "IP",        :float
    t.column "W",         :integer
    t.column "SV",        :integer
    t.column "K",         :integer
    t.column "ERA",       :float
    t.column "WHIP",      :float
    t.column "R",         :integer
    t.column "HR",        :integer
    t.column "RBI",       :integer
    t.column "SB",        :integer
    t.column "AVG",       :float
    t.column "orank",     :integer
    t.column "ab",        :string
    t.column "prank",     :integer
    t.column "depth",     :integer
    t.column "note",      :string
    t.column "pHR",       :integer
    t.column "pR",        :integer
    t.column "pRBI",      :integer
    t.column "pSB",       :integer
    t.column "pBA",       :float
    t.column "pK",        :integer
    t.column "pW",        :integer
    t.column "pSV",       :integer
    t.column "pERA",      :float
    t.column "pWHIP",     :float
  end

  add_index "players", ["player"], :name => "players_player_index"
  add_index "players", ["pos"], :name => "players_pos_index"
  add_index "players", ["team"], :name => "players_team_index"
  add_index "players", ["rank"], :name => "players_rank_index"

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "sessions_session_id_index"

  create_table "teams", :force => true do |t|
    t.column "full_name",      :string
    t.column "short_name",     :string
    t.column "owner",          :string
    t.column "team_yahoo_ref", :integer
    t.column "draft_order",    :integer, :default => 1
  end

  create_table "users", :force => true do |t|
    t.column "login",    :string
    t.column "password", :string
    t.column "email",    :string
    t.column "team_id",  :integer
    t.column "role",     :string
  end

end
